allowBuilds:
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
allowedBuiltDependencies: better-sqlite3 electron esbuild
onlyBuiltDependencies: better-sqlite3 electron esbuild
